---

- name: Install repository Nodejs_10
  shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -
  tags: nodejs


- name: Install repository Yarn package manager
  shell: curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
  tags: nodejs


- name: Install Node.js and npm
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - nodejs
    - yarn
    - gcc-c++ 
    - make
  tags: nodejs


- name: Adding port 3000/TCP
  firewalld:
    port: 3000/tcp
    permanent: true
    immediate: true
    state: enabled
  tags: nodejs
