---

- name: Remove repository Nodejs_10
  yum_repository:
    name: nodesource-el7.repo
    state: absent
  notify: yum-clean-metadata
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"  
  tags: nodejs


- name: Remove repository Yarn package manager
  yum_repository:
    name: yarn
    state: absent
  notify: yum-clean-metadata
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: nodejs


- name: Remove Node.js and npm
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - nodejs
    - yarn
    - gcc-c++ 
    - make
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: nodejs


- name: Remove Node.js version 16 from repository for EL8/EL9
  shell: dnf module remove nodejs:16
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: nodejs


- name: Removing port 3000/TCP
  firewalld:
    port: 3000/tcp
    permanent: true
    immediate: true
    state: disabled
  tags: nodejs
